# Generated by Django 5.0.3 on 2024-04-12 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project_page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_image', models.ImageField(upload_to='Project_page')),
                ('project_names', models.CharField(default='...', max_length=255)),
                ('project_diss', models.CharField(default='...', max_length=255)),
                ('project_urls', models.CharField(default='#', max_length=255)),
                ('project_main_diss', models.CharField(default='...', max_length=1024)),
                ('project_languages', models.CharField(default='#', max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='work_page',
            name='work_main_diss',
        ),
    ]
