# Generated by Django 5.0.3 on 2024-04-24 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_project_languages_urls_projectpage_project_languages_urls1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectpage',
            name='project_image',
            field=models.FileField(upload_to='projectPage'),
        ),
    ]
