# Generated by Django 5.0.3 on 2024-04-24 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_projectpage_project_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='index_work_page',
            name='work_url',
        ),
        migrations.AlterField(
            model_name='projectpage',
            name='project_image',
            field=models.ImageField(upload_to='projectPage'),
        ),
    ]
