# Generated by Django 5.0.3 on 2024-04-24 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_index_work_page_work_url_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectpage',
            old_name='project_urls',
            new_name='live_privew',
        ),
    ]
