# Generated by Django 5.0.3 on 2024-04-24 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_rename_project_urls_projectpage_live_privew'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectpage',
            old_name='live_privew',
            new_name='live_preview',
        ),
    ]
