# Generated by Django 5.0.3 on 2024-04-24 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_rename_live_privew_projectpage_live_preview'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpage',
            name='project_preview_img',
            field=models.ImageField(default='...', upload_to='projectPage'),
        ),
    ]
